# ---------------------------------------------------------
# AUTO-README REGENERATOR FOR I_AM PLATFORM
# Powered by Codex + Strategist Agent + AutoWrite
# ---------------------------------------------------------

Write-Host "Updating README.md using Codex…"

# 1. Capture a snapshot of project structure
$tree = (Get-ChildItem -Recurse -File |
    Select-Object -ExpandProperty FullName |
    Sort-Object)

$treeText = $tree -join "`n"

# 2. Collect agent definitions
$agents = (Get-ChildItem agents -Filter "*.agent.md" |
    Select-Object -ExpandProperty FullName |
    Sort-Object)

$agentList = $agents -join "`n"

# 3. Collect workflows
$workflows = (Get-ChildItem codex/workflows -Filter "*.md" |
    Select-Object -ExpandProperty FullName |
    Sort-Object)

$workflowList = $workflows -join "`n"

# 4. Prepare prompt for strategist + docs generator
$prompt = @"
You are the Strategist/Documentation hybrid agent for the I AM Platform.

Your job: Regenerate README.md for the entire project using the full context.

OUTPUT MUST BE A SINGLE JSON OBJECT:
{
  "summary": "brief overview of README update",
  "files": [
    {
      "path": "README.md",
      "action": "write",
      "language": "md",
      "contents": "FULL README CONTENT HERE"
    }
  ],
  "checklist": [],
  "notes": ""
}

README CONTENT REQUIREMENTS:
--------------------------------------
Write a modern, clean, production-grade README.md that includes:

1. H1: I AM — Decentralized Credential Platform
2. High-level mission statement
3. Table of contents
4. Features overview
5. Architecture overview (summarize based on project files)
6. Tech stack (Next.js, Prisma, PostgreSQL, S3, etc.)
7. Agent system description (based on agents/)
8. Workflow automation description (based on codex/workflows/)
9. Business overview (pull from docs/business_plan/)
10. Roadmap (based on strategist analysis)
11. Developer setup instructions
12. Contributing guidelines
13. Auto-update note: “This README is generated by Codex.”

CONTEXT:
--------------------------------------
PROJECT TREE:
$treeText

AGENTS:
$agentList

WORKFLOWS:
$workflowList

IMPORTANT:
- ALWAYS respond with VALID JSON.
- README.md should be the full, complete file.
"@

# 5. Execute via codex auto-write engine
# Write prompt to a temp file (prevents CLI misinterpreting arguments)
$tempPromptPath = Join-Path $env:TEMP "codex_readme_prompt.txt"
Set-Content -Path $tempPromptPath -Value $prompt -Encoding UTF8

# Feed prompt via stdin (100% safe / correct way for large prompts)
$result = Get-Content $tempPromptPath -Raw | codex exec --skip-git-repo-check
$jsonStart = $result.IndexOf("{")
if ($jsonStart -lt 0) {
    Write-Host "Codex did not return JSON. Raw output:"
    Write-Host $result
    exit 1
}

$jsonText = $result.Substring($jsonStart).Trim()

try {
    $data = $jsonText | ConvertFrom-Json
} catch {
    Write-Host "Failed to parse JSON. Raw:"
    Write-Host $result
    exit 1
}

# 6. Write README.md automatically
foreach ($file in $data.files) {
    if ($file.action -eq "write") {
        $path = $file.path
        $contents = $file.contents

        Set-Content -Path $path -Value $contents -Encoding UTF8

        Write-Host "WROTE FILE: $path"
    }
}

Write-Host "`nREADME.md updated successfully."

